services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    ports:
      - "${API_PORT:-4000}:4000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET:-nexus-dev-secret-change-in-production}
      API_PORT: "4000"
      NODE_ENV: production
      ALCHEMY_API_KEY: ${ALCHEMY_API_KEY:-}
      HELIUS_API_KEY: ${HELIUS_API_KEY:-}
      TWITTER_BEARER_TOKEN: ${TWITTER_BEARER_TOKEN:-}
      OPENSEA_API_KEY: ${OPENSEA_API_KEY:-}
      RESERVOIR_API_KEY: ${RESERVOIR_API_KEY:-}

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    ports:
      - "${WEB_PORT:-3000}:3000"
    environment:
      NODE_ENV: production
      API_URL: http://api:4000/api
      NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID: ${NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID:-697e0d756cf3d408f188870e14793c1c}
    depends_on:
      - api
